spring.config.import=optional:file:.env[.properties]
spring.main.allow-circular-references=true
server.port=8083
server.address=0.0.0.0
spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB

apapedia.user.url=http://apap-188.cs.ui.ac.id/api
apapedia.catalog.url=http://apap-189.cs.ui.ac.id/api/catalog
apapedia.category.url=http://apap-189.cs.ui.ac.id/api/category
apapedia.order.url=http://apap-190.cs.ui.ac.id/api/order
apapedia.cart.url=http://apap-190.cs.ui.ac.id/api/cart
apapedia.frontend.url=http://apap-191.cs.ui.ac.id

apapedia.app.jwtSecret=apapediasecret
apapedia.app.jwtExpirationMs=86400000