version: "3.3"
services:
  catalog-web:
    build:
      context: ./catalog
    restart: always
    ports:
      - "10189:8081"
    volumes:
      - ./file-storage:/file-storage
      - ./log:/log
    env_file:
      - catalog/.env
    depends_on:
      - catalog-db
    networks:
      - frontend-network
      - backend-network

  catalog-db:
    image: postgres:14-alpine
    ports:
      - "15189:5432"
    restart: "no"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret99
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - backend-network

  order-web:
    build:
      context: ./order
    restart: always
    ports:
      - "10190:8080"
    volumes:
      - ./file-storage:/file-storage
      - ./log:/log
    env_file:
      - order/.env
    depends_on:
      - order-db
    networks:
      - frontend-network
      - backend-network

  order-db:
    image: postgres:14-alpine
    ports:
      - "15190:5432"
    restart: "no"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret99
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - backend-network

  user-web:
    build:
      context: ./user
    restart: always
    ports:
      - "10188:8082"
    volumes:
      - ./file-storage:/file-storage
      - ./log:/log
    env_file:
      - user/.env
    depends_on:
      - user-db
    networks:
      - frontend-network
      - backend-network

  user-db:
    image: postgres:14-alpine
    ports:
      - "15188:5432"
    restart: "no"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret99
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - backend-network

  frontend-web:
    build:
      context: ./frontend
    restart: always
    ports:
      - "10191:8083"
    volumes:
      - ./file-storage:/file-storage
      - ./log:/log
    env_file:
      - frontend/.env
    networks:
      - frontend-network
      - backend-network

volumes:
  db:
    driver: local

networks:
  frontend-network:
    driver: bridge
  backend-network:
    driver: bridge
